### ISSUE TITLE
Блок правок от Лео

### ISSUE THREAD

**Issue by LubaPM** [MalahVitalij/rocket-programacao#37]
http://prntscr.com/l7349h

1. Pri navedenii mishkoi, knopka ostayotsya aktivnoi kogda kontent otkrit.
2. Eto 2 raznih linka. Pri navedenii mishkoi doljni reagirovat’ po otdel’nosti.
3. Eto chast’ ne doljna prigat’ kogda accordion aktivnii
4. Zdes’ ne nujen tolstii shrift.

**Comment by VladyslavKovalchuk** [comment]
осталось сделать 4 пункт
