### ISSUE TITLE
стр микс - убрать горизонтальный скролл хром моб, фф, опера, ие11

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-programacao#97]
http://prntscr.com/ldhhu7

**Comment by Username-Valeriy** [comment]
не нашел

**Comment by Username-Valeriy** [comment]
не нашел не в одном браузере

**Comment by VladyslavKovalchuk** [comment]
http://prntscr.com/lexnrb появился огромный отступ перед слайдером во всех браузерах
скролл остался в опере, хроме http://prntscr.com/lexwfz
